---
title: 'Section 1: Building A Data Science Toolbox'
author: 'MTH 365: Introduction to Data Science'
date: "`r Sys.Date()`"
output: html_document
---

## Recommended Reading

Today's goal is to get you comfortable working with R, RStudio, and RMarkdown. Some references include:

- _R for Data Science_ Ch. 4: Workflow Basics
- _R for Data Science_ Ch. 27: RMarkdown
- _RMarkdown: The Definitive Guide_ Ch. 2: Basics
- _Getting Used to R, RStudio, and RMarkdown_

## Filling in our toolbox: R and RStudio

1. R (https://cran.r-project.org/)
2. RStudio (https://www.rstudio.com/)
3. `tidyverse` (https://www.tidyverse.org/)

## R

`R` is a free software environment and programming language for statistical computing and graphics

- Initially developed by Ross Ihaka and Robert Gentleman at University of Auckland, New Zealand
- First release: 1995
- Stable beta: 2000
- Maintained by the _R Core Development Team_ and the _Comprehensive R Archive Network (CRAN)_

## R



## R packages



## Why RStudio?



## RStudio Console Tour



## R Markdown



## Reproducible research

Excerpt from the _Simply Statistics_ blog: "The Real Reason Reproducible Research is Important""

> _By using the word reproducible, I mean that the original data (and original computer code) can be analyzed (by an independent investigator) to obtain the same results of the original study. In essence, it is the notion that the data analysis can be successfully repeated._

> ... Reproducibility is important because __it is the only thing that an investigator can guarantee about a study.__

- https://simplystatistics.org/2014/06/06/the-real-reason-reproducible-research-is-important/

## Reproducible research

More reasons to do your programming in a reproducible way:



## Lab 1: Hello R!

The best way to learn about how R, RStudio, and RMarkdown work is to dive right in!

<div class="green2">

Open __Lab 1: Hello R!__ in BlueLine (you can find it in the "Assignments" tab)

You have the rest of the class period to work. When you're finished, submit the compiled HTML document on BlueLine.
</div>
