---
title: 'Lab 10: Building a Spam Filter'
subtitle: "MTH 365: Intro to Data Science"
author: "Your Name Here"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: html_document
---

So far we've seen three techniques for classification:

1. Classification trees and random forests
2. $k$-nearest neighbors
3. Artificial neural networks

Let's try all three on a single task, and see which one produces the "best" results.

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(mosaic)

# install.packages('openintro')
library(openintro)
data(email)

email <- email %>% select(-time) %>% na.omit()
glimpse(email)
```

> 1. Create a testing and training data set, using an 80-20 split (80% training, 20% testing).

## Technique 1: Random forests and classification trees

> 2. Use a random forest to determine which variable(s) are most important for classifying an email as spam.

> 3. Build a classification tree using these important variables.

> 4. Apply the classification tree to your testing data set, and build a confusion matrix. How well does the classification tree categorize emails into spam or non-spam?

## Technique 2: $k$-nearest neighbors

> 5. $k$-nearest neighbors assumes that all explanatory variables are numeric. Before fitting the model, you'll need to remove two variables from your training and testing data. Which ones?

> 6. Use $k$-nearest neighbors on the training data set to classify emails as spam or non-spam. 

> 7. Apply the $k$-nearest neighbors technique to your testing data set, and build a confusion matrix. How well does the $k$-nearest neighbors algorithm categorize emails into spam or non-spam?


## Technique 3: Artificial neural networks

> 8. Build a single-layer artificial neural network with 20 nodes. 

> 9. Apply the ANN to your testing data set, and build a confusion matrix. How well does the ANN categorize emails into spam or non-spam?

## Recommendation

> 10. Of the three techniques you tested, which do you recommend for implementing a spam filter? Explain your recommendation.