---
title: 'Lab 11: US Statewide Crime'
subtitle: "MTH 365: Intro to Data Science"
author: "Your Name Here"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: html_document
---

The data set `us_statewide_crime.csv` contains the following crime statistics for all US states and the District of Columbia in 2010.

Variable|Description
---|---
`State`|State name
`Violent_Crime`|Violent crime rate (per 100,000 residents)
`Murder_Rate`|Murder rate (per 100,000 residents)
`Poverty`|Percent of residents below the poverty rate
`High_School`|Percent of residents with a high school degree
`College`|Percent of residents with a four-year college degree
`Single_Parent`|Percent of children living in single parent families
`Unemployed`|Unemployment rate
`Metropolitan`|Percent of residents living in a metropolitan area

> 1. Download this data set from BlueLine, and import it into RStudio. Use the `glimpse()` function to make sure your data has imported correctly.

We'd like to investigate two research questions:

1. Which states are most similar?
2. Which factors can explain most of the "variability" in the data?

> 2. What technique(s) are appropriate for each research question? Explain your reasoning.

---

## Which states are most similiar?

We'll use both hierarchical clustering and $k$-means clustering to group states based on similarity.

> 3. Create a new data set that contains _only_ the numerical variables, and assign the states' names as the row names of your new data set.

> 4. Use your new data set to calculate the "distance" between each states. Display a few rows and columns of your distance matrix.

> 5. Use hierarchical clustering to cluster states. How many clusters are there? Which groups of states are similar? Can you explain why these similarities might exist?

> 6. Create a fan diagram of your clustering. Use the number of clusters you selected in Question 5 to change the colors of the state labels.

> 7. Use $k$-means clustering to cluster the data into the number of clusters you selected in Question 5. How do the clusters change?

---

## Which factors explain most of the variability in the data?

There are likely some strong correlations present in this data! We can use principal components analysis to "group" some of these variables into "factors" that might more broadly address the variability in the data.

> 8. Use principal components analysis to identify the most important components in this data. How much variability is explained by the first few principal components?

> 9. Based on a scree plot, how many principal components should be "retained" in this data?

> 10. Visualize the first two principal components. Which variable(s) provide significant contributions to these components? 

> 11. Do the principal components have "interpretability"? That is, what does the first PC represent? What does the second PC represent? If the components aren't interpretable, explain your reasoning.

